name: dax2sql
version: '0.0.0'
github: "githubuser/dax2sql"
license: MIT
author: "Kiara Grouwstra <kiara.grouwstra@gmail.com>"
maintainer: "Kiara Grouwstra <kiara.grouwstra@gmail.com>"
synopsis: generate SQL queries from DAX expressions
# description: dax2sql is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

dependencies:
- base
- text
- attoparsec
- attoparsec-expr
- scientific

library:
  dependencies: []
  source-dirs: library

executables:
  dax2sql:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - dax2sql
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  dax2sql-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - dax2sql
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  dax2sql-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - dax2sql
    - tasty
    - tasty-hspec
    - sqlite-simple
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
